### ISSUE TITLE
Run the container in the CI

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Demo-vcity-py3dtilers-lyon-docker#1]
Add a `docker run` within the CI: for this [refer e.g. to this example](https://github.com/VCityTeam/UD-Demo-DatAgora-Deambulation-Bron-docker/blob/master/.travis.yml#L15)

**Comment by LorenzoMarnat** [comment]
Done in commit 823fce1f6372f5c66c977ef36f07c7cc573217a4
